import { execFileSync, spawnSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'yaml'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { findAiAttribution } from './check-ai-attribution.mjs'

// Every identity below is real: it was taken from `git log` in this repo, so the human cases are
// people who have actually co-authored here and would be blocked by a sloppier rule.
const message = (...lines) => ['fix(scope): do the thing', '', ...lines].join('\n')

describe('AI attribution in commit messages', () => {
  it('catches the trailer that reached main, in the shapes a tool emits', () => {
    const variants = [
      'Co-authored-by: Claude Sonnet 5 <noreply@anthropic.com>',
      'co-authored-by:Claude <noreply@anthropic.com>',
      'CO-AUTHORED-BY:   Claude Opus 5 (1M context) <noreply@anthropic.com>',
      'Co-Authored-By: Claude Code <noreply@anthropic.com>',
      'Co authored by: Claude Fable 5.1 <noreply@anthropic.com>',
      'Co-authored-by: Codex <noreply@openai.com>',
      'Co-authored-by: Codex <codex@users.noreply.github.com>',
      'Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>',
      'Co-authored-by: Cursor <cursoragent@cursor.com>',
      'Co-authored-by: Devin <158243242+devin-ai-integration[bot]@users.noreply.github.com>',
      'Co-authored-by: claude[bot] <claude[bot]@users.noreply.github.com>',
      'Co-authored-by: Grok Companion <noreply@x.ai>',
      'Co-authored-by: Amp <amp@ampcode.com>',
      'Signed-off-by: Claude <noreply@anthropic.com>',
      'Assisted-by: Gemini CLI <gemini-cli[bot]@users.noreply.github.com>',
      'Co-authored-by: Claude Opus 5',
      'Co-authored-by:\tClaude Sonnet 5 <noreply@anthropic.com>\r'
    ]
    for (const variant of variants) {
      expect(findAiAttribution(message(variant)), variant).toHaveLength(1)
    }
  })

  it('catches the tool signature line even without a trailer', () => {
    expect(
      findAiAttribution(message('🤖 Generated with [Claude Code](https://claude.com/claude-code)'))
    ).toHaveLength(1)
    expect(findAiAttribution(message('Generated with Codex'))).toHaveLength(1)
  })

  // The heart of the gate: the rule is against crediting a machine, not against Co-authored-by.
  it('leaves human co-authors alone, including the ones that look like tools', () => {
    const humans = [
      'Co-authored-by: Fabian Altahona <scloud@netsat.co>',
      'Co-authored-by: Neil Parker <nwparker@anthropic.com>',
      'Co-authored-by: LauraGPT <LauraGPT@users.noreply.github.com>',
      'Co-authored-by: Devin345458 <devin@appleidimagination.com>',
      'Co-authored-by: federico-ntb <federico@notchatbot.com>',
      'Co-authored-by: Daniil Zinenko <dzinenko@welmi.ai>',
      'Co-authored-by: Claude Dupont <claude.dupont@example.fr>',
      'Co-authored-by: Amplify Team <team@example.com>',
      'Signed-off-by: Jinwoo-H <jinwoo0825@gmail.com>'
    ]
    for (const human of humans) {
      expect(findAiAttribution(message(human)), human).toEqual([])
    }
  })

  // Provenance is not credit, and this trailer is required on every commit here — a gate that
  // flagged it would fail its own installing commit.
  it('accepts the Claude-Session provenance trailer', () => {
    expect(
      findAiAttribution(
        message('Claude-Session: https://claude.ai/code/session_019BFeAfzxvVEyxVTkZFjBdQ')
      )
    ).toEqual([])
  })

  // This repo ships AI integrations, so assistant names appear in ordinary prose constantly.
  it('does not read prose about an assistant as credit', () => {
    expect(
      findAiAttribution(
        [
          'fix(claude): que una identidad en varios perfiles no comparta cadena de refresh',
          '',
          'The title Claude generated is truncated, and the Codex pane kept the old one.',
          'Session summaries are generated by the worker before the pane closes.'
        ].join('\n')
      )
    ).toEqual([])
  })

  it('reports the line and why, so the next reader does not investigate from zero', () => {
    const [finding] = findAiAttribution(
      message('Co-authored-by: Claude Sonnet 5 <noreply@anthropic.com>')
    )
    expect(finding.lineNumber).toBe(3)
    expect(finding.line).toBe('Co-authored-by: Claude Sonnet 5 <noreply@anthropic.com>')
    expect(finding.reason).toContain('noreply@anthropic.com')
  })
})

describe('AI attribution gate wiring', () => {
  const steps = parse(readFileSync('.github/workflows/pr.yml', 'utf8')).jobs.static_analysis.steps
  const gateIndex = steps.findIndex((step) => step.run?.includes('pnpm run check:ai-attribution'))

  it('runs on the PR with the merge target as its base', () => {
    expect(gateIndex).toBeGreaterThanOrEqual(0)
    expect(steps[gateIndex].run).toContain('github.event.pull_request.base.sha')
  })

  // Why after the fetch: without refs/remotes/upstream/main the gate cannot exclude upstream's
  // commits, and a sync PR imports thousands of them.
  it('runs after upstream history is fetched', () => {
    const fetchIndex = steps.findIndex(
      (step) => step.name === 'Fetch upstream history for base resolution'
    )
    expect(fetchIndex).toBeGreaterThanOrEqual(0)
    expect(fetchIndex).toBeLessThan(gateIndex)
  })
})

// The range is the other half of the gate: parsing a message right is useless if the gate judges
// commits the PR did not write. These run against a real repository because that is the only
// thing that exercises the rev-list exclusions.
describe('the range the gate judges', () => {
  const AI_TRAILER = 'Co-authored-by: Claude Sonnet 5 <noreply@anthropic.com>'
  const script = fileURLToPath(new URL('check-ai-attribution.mjs', import.meta.url))
  let repo = ''

  const git = (...args) => execFileSync('git', args, { cwd: repo, encoding: 'utf8' })
  const commit = (subject, ...body) =>
    git('commit', '--allow-empty', '--no-gpg-sign', '-m', [subject, '', ...body].join('\n'))
  const run = (base, upstreamRefs = '') => {
    const result = spawnSync(process.execPath, [script, base], {
      cwd: repo,
      encoding: 'utf8',
      env: { ...process.env, ORCA_AI_ATTRIBUTION_UPSTREAM_REFS: upstreamRefs }
    })
    return { status: result.status, output: `${result.stdout}${result.stderr}` }
  }

  beforeAll(() => {
    repo = mkdtempSync(join(tmpdir(), 'orca-ai-attribution-'))
    git('init', '--quiet', '--initial-branch', 'main')
    git('config', 'user.name', 'Fabian Altahona')
    git('config', 'user.email', 'scloud@netsat.co')
    commit('chore: first commit')
    git('branch', 'fake-upstream')
    // The two commits that already landed on main with AI credit (ORCA-529).
    commit('fix: landed before the gate existed', AI_TRAILER)
    git('checkout', '--quiet', '-b', 'feature')
  })

  afterAll(() => {
    rmSync(repo, { recursive: true, force: true })
  })

  it('passes a clean PR even though main carries the commits that started this', () => {
    commit('feat: clean work', 'Claude-Session: https://claude.ai/code/session_x')
    expect(run('main').status).toBe(0)
  })

  it('fails on the PR commit that carries the trailer, and names it', () => {
    commit('feat: credited a tool', AI_TRAILER)
    const { status, output } = run('main')
    expect(status).toBe(1)
    expect(output).toContain('credited a tool')
    expect(output).not.toContain('landed before the gate existed')
    git('reset', '--quiet', '--hard', 'HEAD~1')
  })

  it('passes a PR commit co-authored by a person', () => {
    commit('feat: pair work', 'Co-authored-by: Jinwoo-H <jinwoo0825@gmail.com>')
    expect(run('main').status).toBe(0)
  })

  // A sync PR merges upstream, whose commits credit assistants under rules this fork does not
  // set. Judging them would make every sync red for work nobody here wrote.
  it('excludes commits imported from upstream, and would fail without that exclusion', () => {
    git('checkout', '--quiet', 'fake-upstream')
    commit('fix: upstream work', AI_TRAILER)
    git('checkout', '--quiet', 'feature')
    git(
      'merge',
      '--quiet',
      '--no-ff',
      '--no-gpg-sign',
      '-m',
      'chore(sync): merge upstream',
      'fake-upstream'
    )

    expect(run('main', 'fake-upstream').status).toBe(0)
    expect(run('main', '').status).toBe(1)
  })

  it('skips instead of failing when the base is missing from the checkout', () => {
    const { status, output } = run('origin/nonexistent')
    expect(status).toBe(0)
    expect(output).toContain('skipped')
  })
})
